### PR TITLE
Use cvt to simplify syscall error handling

### PR DESCRIPTION
**Pull request by marmistrz**

### CODE REVIEW

**Comment by marmistrz** [comment]
The CI failure is unrelated to this change.

**Comment by alexcrichton** [comment]
Thanks for the PR! I think though I'd prefer to avoid picking up a crates.io dependency for this, could the function be inlined into this crate?

**Comment by marmistrz** [comment]
Basically, I created the `cvt` precisely to be able to share this small piece of code between projects. We're already using it in CraneStation/wasi-common (precisely in the winx subcrate so far) and this dependency (however small) would be reused if we also used the crate here.

**Comment by alexcrichton** [comment]
Makes sense yeah, and seems reasonable! I actually also wrote this support in the standard library :)

I would prefer to not pick up a dependency on a crate, though. I'm ok with inlining a helper function here, but if this is just to add a crate dependency I think it's ok to close this.

**Comment by marmistrz** [comment]
If we're not delegating the functionality to a dedicated crate, then I'm unsure of such a PR and I'll basically be  indifferent to this idea. It's up to you if we're not adding the dependency.

**Comment by alexcrichton** [comment]
Ok, in that case I'm gonna go ahead and close because I'd prefer to not pick up a dependency for this.

**Pull request closed without merging**
